before_script:  
  ##
   ## Create the SSH directory and give it the right permissions
   ##
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   
   ##
   ## Install ssh-agent if not already installed, it is required by Docker.
   ## (change apt-get to yum if you use an RPM-based image)
   ##
   - whoami
   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

   ##
   ## Run ssh-agent (inside the build environment)
   ##
   - eval $(ssh-agent -s)

   ##
   ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
   ## We're using tr to fix line endings which makes ed25519 keys work
   ## without extra base64 encoding.
   ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
   ##
   #- ssh-add <(echo "$SSH_PRIVATE_KEY")
   - echo "$SSH_PRIVATE_KEY_ECAB" | tr -d '\r' | ssh-add - > /dev/null

stages:
  #- test
  #- build
  - deploy

deploy_production:
  artifacts:
    when: always
  stage: deploy
  environment:
    name: staging
    url: omgtu.ru
  script:
    - ssh -oStrictHostKeyChecking=accept-new d_volkov@omgtu.ru "cd /data/www/up && git checkout master && git pull origin master && exit"
  only:
  - master
  tags:
    - up.omgtu.ru
